POST http://127.0.0.1:8086/login
Content-Type: application/json

{
	"phone": 250,
	"user_name": "hhh",
	"avatar": "wrfvrvwr",
	"user_nickname": "regrg"
}
###

POST http://127.0.0.1:8086/test
Content-Type: application/json

{
	"type":"message"
}

###
POST  http://127.0.0.1:8086/index
Content-Type: application/json

###
POST  http://127.0.0.1:8086/index/detail
Content-Type: application/json

{
	"h_id":2
}


###
POST  http://127.0.0.1:8086/index/detail/pay
Content-Type: application/json

{
  "begin_date": null,
  "end_date": null,
  "h_id": 3,
  "phone": "18030931611",
  "rent_time": 4
}

###
POST  http://127.0.0.1:8086/index/detail/collection
Content-Type: application/json

{

  "h_id": 2,
  "phone": "18030931611"
}

###
POST  http://127.0.0.1:8086/index/detail/cancelcollection
Content-Type: application/json

{
  "h_id": 2,
  "phone": "18030931611"
}

###
POST  http://127.0.0.1:8086/index/detail/book
Content-Type: application/json

{
  "h_id": 5,
  "phone": "2",
  "visit_number": 3,
  "visit_time": null
}

###
POST  http://127.0.0.1:8086/tenants/orders
Content-Type: application/json

{
  "phone": "18030931611"
}

###
POST  http://127.0.0.1:8086/tenants/orders/relet
Content-Type: application/json

{
  "order_id": 1,
  "relet_time": 1
}

###
POST  http://127.0.0.1:8086/tenants/collections
Content-Type: application/json

{
  "phone": "2"
}

###
POST  http://127.0.0.1:8086/landlord/orders
Content-Type: application/json

{
  "phone": "1"
}


###
POST  http://127.0.0.1:8086/landlord/allold
Content-Type: application/json

{
  "phone": "1"
}

###
POST  http://127.0.0.1:8086/landlord/rentnew
Content-Type: application/json

{
  "address": "江南皮革厂",
  "h_detail": null,
  "h_latitude": null,
  "h_longitude": null,
  "h_name": "大别野vfsrwf",
  "max_relettime": null,
  "max_renttime": null,
  "phone": "1",
  "price": 999,
  "pictures":[]
}

###
POST  http://127.0.0.1:8086/landlord/rentold
Content-Type: application/json

{
  "h_id":2,
  "address": "江南皮革厂",
  "h_detail": null,
  "h_latitude": null,
  "h_longitude": null,
  "h_name": "天堂",
  "max_relettime": null,
  "max_renttime": null,
  "price": 999
}

###
POST  http://127.0.0.1:8086/landlord/deleteold
Content-Type: application/json

{
  "h_id":3
}

###
POST  http://127.0.0.1:8086/landlord/book
Content-Type: application/json

{
  "phone":2
}

###
POST  http://127.0.0.1:8086/root/audited
Content-Type: application/json

{
  "phone":"18030931611"
}

###
#审核状态退回至未审核则可以被二次审核，被退回至已驳回则不可被二审
POST  http://127.0.0.1:8086/root/delaudited
Content-Type: application/json

{
  "audit_id":1,
  "audit_info":"之前看错了",
  "audit_state":"未审核"
}

###
POST  http://127.0.0.1:8086/root/audits
Content-Type: application/json

###
POST  http://127.0.0.1:8086/root/audit
Content-Type: application/json

{
  "h_id":3,
  "phone":18030931611,
  "audit_state":"已驳回",
  "audit_info":"不行"
}

###
POST  http://127.0.0.1:8086/messages
Content-Type: application/json

{
  "phone":18030931611,
  "user_type":"租客"
}

###
POST  http://127.0.0.1:8086/messages/read
Content-Type: application/json

{
  "message_id":1
}

###
POST  http://127.0.0.1:8086/messages/send
Content-Type: application/json

{
  "content": "您以支付成功",
  "message_type": "支付成功通知",
  "phone": "1",
  "user_type": ""
}

###
POST  http://127.0.0.1:8086/test/picture
Content-Type: application/json

{
  "h_id":1,
  "pictures":[
    
  ]
}